server:
  port: ${vcap.application.port:8080}
  servlet:
    context-path: /tlm-generator
configtemplates:
  templates:
    - name: 'channel-project'
      display-name: 'Proyectos servicio de canal'
      language: 'java'
      framework: 'Spring'
      git-url: 'https://github.com/JeffreyMalca/generadorTemplate.g8.git'
      groups:
        - name: 'datos'
          display-name: 'Descripcion del proyecto'
          description: 'Plantilla de canal con librerias de arquitectura y devops'
          icon: 'subtitles'
          properties:
            - name: 'project'
              display-name: 'Proyecto'
              input-type: 'text'
              default-value: 'talma'
              active: 'true'
              childs: ''
            - name: 'application'
              display-name: 'Aplicacion'
              input-type: 'text'
              default-value: 'capacity'
              active: 'true'
              childs: ''
        - name: 'modulos'
          display-name: 'Modulos'
          description: 'Modulos de ejemplo que tiene esta plantilla'
          icon: 'folder_open'
          properties:
            - name: 'module1'
              display-name: 'Nombre del primer submodulo'
              input-type: 'text'
              default-value: 'Ejem. pax'
              active: 'true'
              childs: ''
            - name: 'module2'
              display-name: 'Nombre del segundo submodulo'
              input-type: 'text'
              default-value: 'Ejem. rampa'
              active: 'true'
              childs: ''
            - name: 'module3'
              display-name: 'Nombre del tercer submodulo'
              input-type: 'text'
              default-value: 'Ejem. capacity'
              active: 'true'
              childs: ''
        - name: 'dependencias'
          display-name: 'Dependencias de Talma'
          description: 'Librerias existentes'
          icon: 'folder_open'
          properties:
            - name: 'pubsub_enable'
              display-name: 'Talma commons pub sub'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'true'
              childs: ''
            - name: 'audit_enable'
              display-name: 'Talma commons auditoria'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'true'
              childs: ''
            - name: 'technicaltrace_enable'
              display-name: 'Talma commons trazabilidad tecnica (logs)'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'true'
              childs: ''
            - name: 'distributedtrace_enable'
              display-name: 'Talma commons trazabilidad distribuida (traceid)'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'true'
              childs: ''
            - name: 'exception'
              display-name: 'Manejo de excepciones'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'false'
              childs: ''
            - name: 'rest-cloud'
              display-name: 'Llamadas Rest entre servicios'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'false'
              childs: ''
            - name: 'Dockerfile'
              display-name: 'Dockerfile'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'false'
              childs: ''
            - name: 'Retry'
              display-name: 'Reintentos para el componente de pubsub'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'false'
              childs: ''
            - name: 'Utils'
              display-name: 'Utilitarios de fecha, string, etc'
              input-type: 'checkbox'
              default-value: 'true'
              active: 'false'
              childs: ''
            - name: 'JWT'
              display-name: 'Utilitario para manipular el jwt'
              input-type: 'checkbox'
              default-value: 'false'
              active: 'false'
              childs: ''
