apiVersion: v1
kind: Service
metadata:
  name: microgenerator-service
  namespace: eu2-ayni-dev-01
  labels:
    app: microgenerator
spec:
  ports:
    - name: http 
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: microgenerator
  type: LoadBalancer